export const INVOICE_CREATE_REQUEST = "INVOICE_CREATE_REQUEST"
export const INVOICE_CREATE_SUCCESS = "INVOICE_CREATE_SUCCESS"
export const INVOICE_CREATE_FAIL = "INVOICE_CREATE_FAIL"

export const INVOICE_READ_REQUEST = "INVOICE_READ_REQUEST"
export const INVOICE_READ_SUCCESS = "INVOICE_READ_SUCCESS"
export const INVOICE_READ_FAIL = "INVOICE_READ_FAIL"

export const INVOICE_UPDATE_REQUEST = "INVOICE_UPDATE_REQUEST"
export const INVOICE_UPDATE_SUCCESS = "INVOICE_UPDATE_SUCCESS"
export const INVOICE_UPDATE_FAIL = "INVOICE_UPDATE_FAIL"

export const INVOICE_DETAILS_REQUEST = "INVOICE_DETAILS_REQUEST"
export const INVOICE_DETAILS_SUCCESS = "INVOICE_DETAILS_SUCCESS"
export const INVOICE_DETAILS_FAIL = "INVOICE_DETAILS_FAIL"

export const INVOICE_DELETE_REQUEST = "INVOICE_DELETE_REQUEST"
export const INVOICE_DELETE_SUCCESS = "INVOICE_DELETE_SUCCESS"
export const INVOICE_DELETE_FAIL = "INVOICE_DELETE_FAIL"



export const INVOICE_READ_SUMMARY_REQUEST = "INVOICE_READ_SUMMARY_REQUEST"
export const INVOICE_READ_SUMMARY_SUCCESS = "INVOICE_READ_SUMMARY_SUCCESS"
export const INVOICE_READ_SUMMARY_FAIL = "INVOICE_READ_SUMMARY_FAIL"




// ? Tenants
export const TENANT_INVOICE_READ_REQUEST = "TENANT_INVOICE_READ_REQUEST"
export const TENANT_INVOICE_READ_SUCCESS = "TENANT_INVOICE_READ_SUCCESS"
export const TENANT_INVOICE_READ_FAIL    = "TENANT_INVOICE_READ_FAIL"

// ? Landlords

export const LANDLORD_INVOICE_READ_REQUEST = "LANDLORD_INVOICE_READ_REQUEST"
export const LANDLORD_INVOICE_READ_SUCCESS = "LANDLORD_INVOICE_READ_SUCCESS"
export const LANDLORD_INVOICE_READ_FAIL    = "LANDLORD_INVOICE_READ_FAIL"