export const LEASE_CREATE_REQUEST = "LEASE_CREATE_REQUEST"
export const LEASE_CREATE_SUCCESS = "LEASE_CREATE_SUCCESS"
export const LEASE_CREATE_FAIL = "LEASE_CREATE_FAIL"

export const LEASE_READ_REQUEST = "LEASE_READ_REQUEST"
export const LEASE_READ_SUCCESS = "LEASE_READ_SUCCESS"
export const LEASE_READ_FAIL = "LEASE_READ_FAIL"
export const LEASE_CREATE_RESET = "LEASE_CREATE_RESET"

export const LEASE_UPDATE_REQUEST = "LEASE_UPDATE_REQUEST"
export const LEASE_UPDATE_SUCCESS = "LEASE_UPDATE_SUCCESS"
export const LEASE_UPDATE_FAIL = "LEASE_UPDATE_FAIL"

export const LEASE_DELETE_REQUEST = "LEASE_DELETE_REQUEST"
export const LEASE_DELETE_SUCCESS = "LEASE_DELETE_SUCCESS"
export const LEASE_DELETE_FAIL = "LEASE_DELETE_FAIL"

