export const LANDLORD_CREATE_REQUEST = 'LANDLORD_CREATE_REQUEST'
export const LANDLORD_CREATE_SUCCESS = 'LANDLORD_CREATE_SUCCESS'
export const LANDLORD_CREATE_FAIL = 'LANDLORD_CREATE_FAIL'
export const LANDLORD_CREATE_RESET = 'LANDLORD_CREATE_RESET'

export const LANDLORD_READ_REQUEST = 'LANDLORD_READ_REQUEST'
export const LANDLORD_READ_SUCCESS = 'LANDLORD_READ_SUCCESS'
export const LANDLORD_READ_FAIL = 'LANDLORD_READ_FAIL'
export const LANDLORD_READ_RESET = 'LANDLORD_READ_RESET'

export const LANDLORD_UPDATE_REQUEST = 'LANDLORD_UPDATE_REQUEST'
export const LANDLORD_UPDATE_SUCCESS = 'LANDLORD_UPDATE_SUCCESS'
export const LANDLORD_UPDATE_FAIL = 'LANDLORD_UPDATE_FAIL'
export const LANDLORD_UPDATE_RESET = 'LANDLORD_DETAILS_RESET'

export const LANDLORD_DELETE_SUCCESS = 'LANDLORD_DELETE_SUCCESS'
export const LANDLORD_DELETE_REQUEST = 'LANDLORD_DELETE_REQUEST'
export const LANDLORD_DELETE_FAIL = 'LANDLORD_DELETE_FAIL'
export const LANDLORD_DELETE_RESET = 'LANDLORD_DELETE_RESET'

export const LANDLORD_DETAILS_REQUEST = 'LANDLORD_DETAILS_REQUEST'
export const LANDLORD_DETAILS_SUCCESS = 'LANDLORD_DETAILS_SUCCESS'
export const LANDLORD_DETAILS_FAIL = 'LANDLORD_DETAILS_FAIL'
export const LANDLORD_DETAILS_RESET = 'LANDLORD_DETAILS_RESET'

