export const MAINTENANCE_CREATE_REQUEST = "MAINTENANCE_CREATE_REQUEST"
export const MAINTENANCE_CREATE_SUCCESS = "MAINTENANCE_CREATE_SUCCESS"
export const MAINTENANCE_CREATE_FAIL = "MAINTENANCE_CREATE_FAIL"

export const MAINTENANCE_READ_REQUEST = "MAINTENANCE_READ_REQUEST"
export const MAINTENANCE_READ_SUCCESS = "MAINTENANCE_READ_SUCCESS"
export const MAINTENANCE_READ_FAIL = "MAINTENANCE_READ_FAIL"

export const MAINTENANCE_UPDATE_REQUEST = "MAINTENANCE_UPDATE_REQUEST"
export const MAINTENANCE_UPDATE_SUCCESS = "MAINTENANCE_UPDATE_SUCCESS"
export const MAINTENANCE_UPDATE_FAIL = "MAINTENANCE_UPDATE_FAIL"

export const MAINTENANCE_DELETE_REQUEST = "MAINTENANCE_DELETE_REQUEST"
export const MAINTENANCE_DELETE_SUCCESS = "MAINTENANCE_DELETE_SUCCESS"
export const MAINTENANCE_DELETE_FAIL = "MAINTENANCE_DELETE_FAIL"

export const MAINTENANCE_DETAILS_REQUEST = "MAINTENANCE_DETAILS_REQUEST"
export const MAINTENANCE_DETAILS_SUCCESS = "MAINTENANCE_DETAILS_SUCCESS"
export const MAINTENANCE_DETAILS_FAIL =    "MAINTENANCE_DETAILS_FAIL"
export const MAINTENANCE_DETAILS_RESET =   "MAINTENANCE_DETAILS_RESET"