export const UNIT_CREATE_REQUEST = 'UNIT_CREATE_REQUEST'
export const UNIT_CREATE_SUCCESS = 'UNIT_CREATE_SUCCESS'
export const UNIT_CREATE_FAIL = 'UNIT_CREATE_FAIL'
export const UNIT_CREATE_RESET = 'UNIT_CREATE_RESET'

export const UNIT_READ_REQUEST = 'UNIT_READ_REQUEST'
export const UNIT_READ_SUCCESS = 'UNIT_READ_SUCCESS'
export const UNIT_READ_FAIL = 'UNIT_READ_FAIL'
export const UNIT_READ_RESET = 'UNIT_READ_RESET'

export const UNIT_UPDATE_REQUEST = 'UNIT_UPDATE_REQUEST'
export const UNIT_UPDATE_SUCCESS = 'UNIT_UPDATE_SUCCESS'
export const UNIT_UPDATE_FAIL = 'UNIT_UPDATE_FAIL'
export const UNIT_UPDATE_RESET = 'UNIT_DETAILS_RESET'

export const UNIT_DELETE_SUCCESS = 'UNIT_DELETE_SUCCESS'
export const UNIT_DELETE_REQUEST = 'UNIT_DELETE_REQUEST'
export const UNIT_DELETE_FAIL = 'UNIT_DELETE_FAIL'
export const UNIT_DELETE_RESET = 'UNIT_DELETE_RESET'

export const UNIT_DETAILS_REQUEST = 'UNIT_DETAILS_REQUEST'
export const UNIT_DETAILS_SUCCESS = 'UNIT_DETAILS_SUCCESS'
export const UNIT_DETAILS_FAIL = 'UNIT_DETAILS_FAIL'
export const UNIT_DETAILS_RESET = 'UNIT_DETAILS_RESET'


export const UNIT_TYPE_READ_REQUEST = 'UNIT_TYPE_READ_REQUEST'
export const UNIT_TYPE_READ_SUCCESS = 'UNIT_TYPE_READ_SUCCESS'
export const UNIT_TYPE_READ_FAIL    = 'UNIT_TYPE_READ_FAIL'
export const UNIT_TYPE_READ_RESET   = 'UNIT_TYPE_READ_RESET'

