export const PROFILE_READ_REQUEST = 'PROFILE_READ_REQUEST'
export const PROFILE_READ_SUCCESS = 'PROFILE_READ_SUCCESS'
export const PROFILE_READ_FAIL = 'PROFILE_READ_FAIL'
export const PROFILE_READ_RESET = 'PROFILE_READ_RESET'

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET = 'PROFILE_DETAILS_RESET'



