export const BILL_CREATE_REQUEST = "BILL_CREATE_REQUEST"
export const BILL_CREATE_SUCCESS = "BILL_CREATE_SUCCESS"
export const BILL_CREATE_FAIL    = "BILL_CREATE_FAIL"

export const BILL_READ_REQUEST = "BILL_READ_REQUEST"
export const BILL_READ_SUCCESS = "BILL_READ_SUCCESS"
export const BILL_READ_FAIL    = "BILL_READ_FAIL"

export const BILL_UPDATE_REQUEST = "BILL_UPDATE_REQUEST"
export const BILL_UPDATE_SUCCESS = "BILL_UPDATE_SUCCESS"
export const BILL_UPDATE_FAIL    = "BILL_UPDATE_FAIL"

export const BILL_DETAILS_REQUEST = "BILL_DETAILS_REQUEST"
export const BILL_DETAILS_SUCCESS = "BILL_DETAILS_SUCCESS"
export const BILL_DETAILS_FAIL    = "BILL_DETAILS_FAIL"

export const BILL_DELETE_REQUEST = "BILL_DELETE_REQUEST"
export const BILL_DELETE_SUCCESS = "BILL_DELETE_SUCCESS"
export const BILL_DELETE_FAIL    = "BILL_DELETE_FAIL"