export const TENANT_CREATE_REQUEST = 'TENANT_CREATE_REQUEST'
export const TENANT_CREATE_SUCCESS = 'TENANT_CREATE_SUCCESS'
export const TENANT_CREATE_FAIL = 'TENANT_CREATE_FAIL'
export const TENANT_CREATE_RESET = 'TENANT_CREATE_RESET'

export const TENANT_READ_REQUEST = 'TENANT_READ_REQUEST'
export const TENANT_READ_SUCCESS = 'TENANT_READ_SUCCESS'
export const TENANT_READ_FAIL = 'TENANT_READ_FAIL'
export const TENANT_READ_RESET = 'TENANT_READ_RESET'

export const TENANT_UPDATE_REQUEST = 'TENANT_UPDATE_REQUEST'
export const TENANT_UPDATE_SUCCESS = 'TENANT_UPDATE_SUCCESS'
export const TENANT_UPDATE_FAIL = 'TENANT_UPDATE_FAIL'
export const TENANT_UPDATE_RESET = 'TENANT_DETAILS_RESET'

export const TENANT_DELETE_SUCCESS = 'TENANT_DELETE_SUCCESS'
export const TENANT_DELETE_REQUEST = 'TENANT_DELETE_REQUEST'
export const TENANT_DELETE_FAIL = 'TENANT_DELETE_FAIL'
export const TENANT_DELETE_RESET = 'TENANT_DELETE_RESET'

export const TENANT_DETAILS_REQUEST = 'TENANT_DETAILS_REQUEST'
export const TENANT_DETAILS_SUCCESS = 'TENANT_DETAILS_SUCCESS'
export const TENANT_DETAILS_FAIL = 'TENANT_DETAILS_FAIL'
export const TENANT_DETAILS_RESET = 'TENANT_DETAILS_RESET'

