export const ACCOUNT_READ_REQUEST = "ACCOUNT_READ_REQUEST"
export const ACCOUNT_READ_SUCCESS = "ACCOUNT_READ_SUCCESS"
export const ACCOUNT_READ_FAIL    = "ACCOUNT_READ_FAIL"

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_UPDATE_REQUEST"
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS"
export const ACCOUNT_UPDATE_FAIL    = "ACCOUNT_UPDATE_FAIL"

export const ACCOUNT_DETAILS_REQUEST = "ACCOUNT_DETAILS_REQUEST"
export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS"
export const ACCOUNT_DETAILS_FAIL    = "ACCOUNT_DETAILS_FAIL"

export const ACCOUNT_DELETE_REQUEST = "ACCOUNT_DELETE_REQUEST"
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS"
export const ACCOUNT_DELETE_FAIL    = "ACCOUNT_DELETE_FAIL"